version: "3.9"

services:
  nginx:
#    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - ./data/html:/var/www/html
    links:
      - wordpress
  wordpress:
    #build: ./requirements/wordpress
    image: wordpress:php7.4-fpm-alpine
    container_name: wordpress
    ports:
      - "9000:9000"
    volumes:
      - ./data/html:/var/www/html
    restart: on-failure
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    links:
      - mariadb
  mariadb:
#    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    restart: on-failure
    volumes:
      - ./data/mysql:/var/lib/mysql
  